apiVersion: v1
kind: Pod
metadata:
  name: nginx-pod
spec:
  containers:
    - name: nginx-container
      image: nginx
      volumeMounts:
        - name: secret-volume
          mountPath: "/etc/test"
      env:
        - name: SERVER_URL_ENV
          valueFrom:
            configMapKeyRef: 
              name: config-map
              key: SERVER_URL
  volumes:
    - name: secret-volume
      secret:
        secretName: k8s-secret
  restartPolicy: Never